#!/bin/bash

get_history() {
    [[ ! -f $1 ]] && mkdir -p $(dirname $1) && touch $1
    [[ ! -s $1 ]] && echo "No history found" || tac $history_file
}

main() {
    history_file="$HOME/.local/share/dmenu-calc/history"
    dmenu_cmd="dmenu -i -l 10 -p"

    input=$(get_history $history_file | ${dmenu_cmd} "Calculator: " "$@") 
    [[ $input == "" ]] && exit

    if grep -q -F "$input" $history_file; then
        equation="$input"
        result="$(printf "$input" | sed 's/^.*\(=\|≈\) //')"
    else
        equation="$(qalc "$input")"
        result="$(qalc -t "$input")"
    fi
    echo "$equation" >> ${history_file}
    printf "$result" | xclip -sel clip
    main "$@"
}
main "$@"
